/*
 * Copyright (C) 2015. Jefferson Lab, xMsg framework (JLAB). All Rights Reserved.
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for educational, research, and not-for-profit purposes,
 * without fee and without a signed licensing agreement.
 *
 * Author Vardan Gyurjyan
 * Department of Experimental Nuclear Physics, Jefferson Lab.
 *
 * IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL,
 * INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF
 * THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, PROVIDED
 * HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE MAINTENANCE,
 * SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

package org.jlab.coda.xmsg.data;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xMsgRegistrationData.proto

public final class xMsgR {
  private xMsgR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface xMsgRegistrationDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string description = 2 [default = "undefined"];
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // required string host = 3;
    /**
     * <code>required string host = 3;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 3;</code>
     */
    java.lang.String getHost();
    /**
     * <code>required string host = 3;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // required sfixed32 port = 4;
    /**
     * <code>required sfixed32 port = 4;</code>
     */
    boolean hasPort();
    /**
     * <code>required sfixed32 port = 4;</code>
     */
    int getPort();

    // required string domain = 5;
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    boolean hasDomain();
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    java.lang.String getDomain();
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    // optional string subject = 6 [default = "undefined"];
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    boolean hasSubject();
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    // optional string type = 7 [default = "undefined"];
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    boolean hasType();
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // optional .xMsgRegistrationData.OwnerType ownerType = 8;
    /**
     * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
     */
    boolean hasOwnerType();
    /**
     * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
     */
    xMsgR.xMsgRegistrationData.OwnerType getOwnerType();
  }
  /**
   * Protobuf type {@code xMsgRegistrationData}
   */
  public static final class xMsgRegistrationData extends
      com.google.protobuf.GeneratedMessage
      implements xMsgRegistrationDataOrBuilder {
    // Use xMsgRegistrationData.newBuilder() to construct.
    private xMsgRegistrationData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private xMsgRegistrationData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final xMsgRegistrationData defaultInstance;
    public static xMsgRegistrationData getDefaultInstance() {
      return defaultInstance;
    }

    public xMsgRegistrationData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private xMsgRegistrationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              host_ = input.readBytes();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              port_ = input.readSFixed32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              domain_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              subject_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              type_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              xMsgR.xMsgRegistrationData.OwnerType value = xMsgR.xMsgRegistrationData.OwnerType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                ownerType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xMsgR.internal_static_xMsgRegistrationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xMsgR.internal_static_xMsgRegistrationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xMsgR.xMsgRegistrationData.class, xMsgR.xMsgRegistrationData.Builder.class);
    }

    public static com.google.protobuf.Parser<xMsgRegistrationData> PARSER =
        new com.google.protobuf.AbstractParser<xMsgRegistrationData>() {
      public xMsgRegistrationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new xMsgRegistrationData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<xMsgRegistrationData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code xMsgRegistrationData.OwnerType}
     *
     * <pre>
     * Type of a an actor that sends the registration data
     * </pre>
     */
    public enum OwnerType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PUBLISHER = 1;</code>
       */
      PUBLISHER(0, 1),
      /**
       * <code>SUBSCRIBER = 2;</code>
       */
      SUBSCRIBER(1, 2),
      ;

      /**
       * <code>PUBLISHER = 1;</code>
       */
      public static final int PUBLISHER_VALUE = 1;
      /**
       * <code>SUBSCRIBER = 2;</code>
       */
      public static final int SUBSCRIBER_VALUE = 2;


      public final int getNumber() { return value; }

      public static OwnerType valueOf(int value) {
        switch (value) {
          case 1: return PUBLISHER;
          case 2: return SUBSCRIBER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OwnerType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OwnerType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OwnerType>() {
              public OwnerType findValueByNumber(int number) {
                return OwnerType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return xMsgR.xMsgRegistrationData.getDescriptor().getEnumTypes().get(0);
      }

      private static final OwnerType[] VALUES = values();

      public static OwnerType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private OwnerType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:xMsgRegistrationData.OwnerType)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 2 [default = "undefined"];
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 2 [default = "undefined"];</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string host = 3;
    public static final int HOST_FIELD_NUMBER = 3;
    private java.lang.Object host_;
    /**
     * <code>required string host = 3;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string host = 3;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required sfixed32 port = 4;
    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>required sfixed32 port = 4;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required sfixed32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    // required string domain = 5;
    public static final int DOMAIN_FIELD_NUMBER = 5;
    private java.lang.Object domain_;
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string domain = 5;</code>
     *
     * <pre>
     * xMsg topic definition
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string subject = 6 [default = "undefined"];
    public static final int SUBJECT_FIELD_NUMBER = 6;
    private java.lang.Object subject_;
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject = 6 [default = "undefined"];</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string type = 7 [default = "undefined"];
    public static final int TYPE_FIELD_NUMBER = 7;
    private java.lang.Object type_;
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 7 [default = "undefined"];</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .xMsgRegistrationData.OwnerType ownerType = 8;
    public static final int OWNERTYPE_FIELD_NUMBER = 8;
    private xMsgR.xMsgRegistrationData.OwnerType ownerType_;
    /**
     * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
     */
    public boolean hasOwnerType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
     */
    public xMsgR.xMsgRegistrationData.OwnerType getOwnerType() {
      return ownerType_;
    }

    private void initFields() {
      name_ = "";
      description_ = "undefined";
      host_ = "";
      port_ = 0;
      domain_ = "";
      subject_ = "undefined";
      type_ = "undefined";
      ownerType_ = xMsgR.xMsgRegistrationData.OwnerType.PUBLISHER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSFixed32(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDomainBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTypeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, ownerType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDomainBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSubjectBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTypeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, ownerType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xMsgR.xMsgRegistrationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xMsgR.xMsgRegistrationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xMsgR.xMsgRegistrationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xMsgR.xMsgRegistrationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xMsgR.xMsgRegistrationData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xMsgRegistrationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements xMsgR.xMsgRegistrationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xMsgR.internal_static_xMsgRegistrationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xMsgR.internal_static_xMsgRegistrationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xMsgR.xMsgRegistrationData.class, xMsgR.xMsgRegistrationData.Builder.class);
      }

      // Construct using xMsgR.xMsgRegistrationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "undefined";
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        subject_ = "undefined";
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = "undefined";
        bitField0_ = (bitField0_ & ~0x00000040);
        ownerType_ = xMsgR.xMsgRegistrationData.OwnerType.PUBLISHER;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xMsgR.internal_static_xMsgRegistrationData_descriptor;
      }

      public xMsgR.xMsgRegistrationData getDefaultInstanceForType() {
        return xMsgR.xMsgRegistrationData.getDefaultInstance();
      }

      public xMsgR.xMsgRegistrationData build() {
        xMsgR.xMsgRegistrationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xMsgR.xMsgRegistrationData buildPartial() {
        xMsgR.xMsgRegistrationData result = new xMsgR.xMsgRegistrationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.subject_ = subject_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ownerType_ = ownerType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xMsgR.xMsgRegistrationData) {
          return mergeFrom((xMsgR.xMsgRegistrationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xMsgR.xMsgRegistrationData other) {
        if (other == xMsgR.xMsgRegistrationData.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000002;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000004;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasDomain()) {
          bitField0_ |= 0x00000010;
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasSubject()) {
          bitField0_ |= 0x00000020;
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000040;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasOwnerType()) {
          setOwnerType(other.getOwnerType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasDomain()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xMsgR.xMsgRegistrationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xMsgR.xMsgRegistrationData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string description = 2 [default = "undefined"];
      private java.lang.Object description_ = "undefined";
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2 [default = "undefined"];</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }

      // required string host = 3;
      private java.lang.Object host_ = "";
      /**
       * <code>required string host = 3;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string host = 3;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        host_ = value;
        onChanged();
        return this;
      }

      // required sfixed32 port = 4;
      private int port_ ;
      /**
       * <code>required sfixed32 port = 4;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required sfixed32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required sfixed32 port = 4;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sfixed32 port = 4;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      // required string domain = 5;
      private java.lang.Object domain_ = "";
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000010);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 5;</code>
       *
       * <pre>
       * xMsg topic definition
       * </pre>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        domain_ = value;
        onChanged();
        return this;
      }

      // optional string subject = 6 [default = "undefined"];
      private java.lang.Object subject_ = "undefined";
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000020);
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject = 6 [default = "undefined"];</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        subject_ = value;
        onChanged();
        return this;
      }

      // optional string type = 7 [default = "undefined"];
      private java.lang.Object type_ = "undefined";
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 7 [default = "undefined"];</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }

      // optional .xMsgRegistrationData.OwnerType ownerType = 8;
      private xMsgR.xMsgRegistrationData.OwnerType ownerType_ = xMsgR.xMsgRegistrationData.OwnerType.PUBLISHER;
      /**
       * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
       */
      public boolean hasOwnerType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
       */
      public xMsgR.xMsgRegistrationData.OwnerType getOwnerType() {
        return ownerType_;
      }
      /**
       * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
       */
      public Builder setOwnerType(xMsgR.xMsgRegistrationData.OwnerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        ownerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .xMsgRegistrationData.OwnerType ownerType = 8;</code>
       */
      public Builder clearOwnerType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ownerType_ = xMsgR.xMsgRegistrationData.OwnerType.PUBLISHER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xMsgRegistrationData)
    }

    static {
      defaultInstance = new xMsgRegistrationData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xMsgRegistrationData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xMsgRegistrationData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xMsgRegistrationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032xMsgRegistrationData.proto\"\205\002\n\024xMsgReg" +
      "istrationData\022\014\n\004name\030\001 \002(\t\022\036\n\013descripti" +
      "on\030\002 \001(\t:\tundefined\022\014\n\004host\030\003 \002(\t\022\014\n\004por" +
      "t\030\004 \002(\017\022\016\n\006domain\030\005 \002(\t\022\032\n\007subject\030\006 \001(\t" +
      ":\tundefined\022\027\n\004type\030\007 \001(\t:\tundefined\0222\n\t" +
      "ownerType\030\010 \001(\0162\037.xMsgRegistrationData.O" +
      "wnerType\"*\n\tOwnerType\022\r\n\tPUBLISHER\020\001\022\016\n\n" +
      "SUBSCRIBER\020\002B\tB\005xMsgRH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_xMsgRegistrationData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_xMsgRegistrationData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xMsgRegistrationData_descriptor,
              new java.lang.String[] { "Name", "Description", "Host", "Port", "Domain", "Subject", "Type", "OwnerType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
